### PR TITLE
Symmetry updates

### PR DESCRIPTION
**Pull request by JasonGibsonUfl**
This is a simple fix to address the electronegativity sorting. By converting `reference_X` from a dictionary of element symbols and electronegativity to a dictionary of element symbols and atomic numbers all unit tests pass. Unit test checking for electronegativity sorting has been changed to atomic number sorting

### CODE REVIEW

**Comment by JasonGibsonUfl** [comment]
`test_composition.py` is changed because the original unit test was made to ensure that 3+ element systems were sorted by electronegativity. Since we have changed the sorting from electronegativity to atomic number, the unit test was changed such that it check the sorting is being properly executed.

**Comment by monk-04** [comment]
Before merging this pull request we need to confirm that `generate_triplets` still works the way we intend it to work.

**Comment by monk-04** [comment]
The [last commit](https://github.com/uf3/uf3/pull/66/commits/f3be4fce9575af76e2828b40730e5abbe4154647) should be made on a different branch. It does not fix any symmetry related issues.

**Review by monk-04 — APPROVED** [review]
Everything looks good! I approve.

**Pull request merged**
