### PR TITLE
Cutoff fix

### PR DESCRIPTION
**Pull request by sunghjung3**
The cutoff that is used to create the supercell and/or construct neighbor lists during featurization has been fixed to be more memory efficient. I have verified that all the resulting feature values and the trained model of the Tungsten example are identical to those before the fix. I have also added a new unit test of a binary system in a periodic cell to further ensure that present and future changes to the featurization algorithm do not erroneously alter the results.

The cutoff that should be used to create the neighbor list of the largest `r_max` across all knot sequences of all interaction types that **involve the center atom**. For example, in the Tungsten example, the 3-body cutoff that is used is `[3.5, 3.5, 7.0]`. Previously it was using a cutoff of 7 Å to construct neighbor lists. As a result, the neighbor list contained 2 neighbor atoms that were as far as 14 Å apart! This pull request fixes this by correctly using a 3.5 Å cutoff.

Regarding performance, it reduced the featurization time of the Tungsten example from 17 minutes 47 seconds to 15 minutes 20 seconds (on my server with 16 cores), which is a 16% increase in speed. I would also guess that it required much less memory, although this was not verified.

### CODE REVIEW

**Review by sxie22 — APPROVED** [review]

**Comment by monk-04** [comment]
@sunghjung3 Just to confirm the two body cutoffs are also considered while deciding r_max?

**Comment by sunghjung3** [comment]
@monk-04 yes. Both 2- and 3-body cutoffs involving the center atoms are considered.

**Comment by monk-04** [comment]
@sunghjung3 I am not able to re-create the following-

> For example, in the Tungsten example, the 3-body cutoff that is used is [3.5, 3.5, 7.0]. Previously it was using a cutoff of 7 Å to construct neighbor lists.

Take a look at the following screenshot-

image

The `r_cut` is 6 Å and not 12 Å. Am I missing something?


But I agree the `get_cutoff` needs to be changed because of the following-

image

In the above case, the `r_cut` should be 7 Å and not 6 Å. Though I doubt anyone will use `[6,7,12]` cutoffs, it still needs to be fixed.

Your changes to `get_cutoff` resolve the above-mentioned issue, but I cannot re-create what you described in your original comment.

**Comment by monk-04** [comment]
@sunghjung3 I don't think I understand the reason behind the choice of algo for the code added to `identify_ij` function.
Specifically, the following lines-

```
knots_flat = np.concatenate([sequence for set_ in knot_sets
                                 for sequence in
                                 set_[:int((1+np.sqrt(1+8*len(set_)))/2-1)]])
```

`identify_ij` function is intended only for 3-body (I am guessing this, as the function is written in `angles.py`)

So this function is only gonna be called (in the current 2 and 3-body framework) with a 3-body `knot_sets`.

So, maybe the following is an easier way to get `r_max` cutoffs from `knot_set`-

```
knots_flat = np.concatenate([sequence for set_ in knot_sets for sequence in set_[:2]])
r_max = np.max(knots_flat)
r_max
```

**Comment by sunghjung3** [comment]
@monk-04 To your first comment, you're right. It was intended to fix the issue when an asymmetric `r_max` (like `[6, 7, 12]`) is provided. I think what happened was that I first tried to fix it by changing `values.append(r_max[0])` to `values.extend(rmax)` to consider all the individual distances, but then realized that only the ones involving the central atom should be considered.

**Comment by sunghjung3** [comment]
@monk-04 To your second comment, you're also right in that for 3-body, the equivalent line would be `knots_flat = np.concatenate([sequence for set_ in knot_sets for sequence in set_[:2]])`.

This is because for 3-body, the knot set has 3 lists (for the 3 distance of a triangle), and plugging in 3 into `len(set_)` in `int((1+np.sqrt(1+8*len(set_)))/2-1)` results in 2.

The reason I wrote it with the formula was just to generalize to an arbitrary body order. I could see this `identify_ij` function being used if we decide to add higher order terms in the future.

**Review by monk-04 — APPROVED** [review]
It looks good to me!

**Pull request merged**
