### PR TITLE
Skip ghost atoms with no real neighbors in force featurization

### PR DESCRIPTION
**Pull request by sunghjung3**
The 3-body force featurization algorithm was modified (conceptually just a 2-line addition) to skip triplets where the center atom is a ghost atom and all of its neighbors are also all ghost atoms. I have verified that the resulting feature values and the model remain the same compared to before the fix in the Tungsten example, and the pytest suites with the featurization unit tests also all pass.

Right now, this PR appears to have lots of changes because it builds on top of #116 . However, it boils down to 2 things:

- Slight refactoring of `generate_triplets()` where the outer-most for-loop (over the center atoms `i_values`) were taken out to its own function called `group_idx_by_center()`
- A single if-statement in `featurize_force_3b()` in `angles.py` that checks if the center atom is a ghost atom and all its neighbors are also ghost atoms

Adding this single if-statement decreased the 3-body force featurization time of the last structure in the Tungsten example from 46.6 seconds to just 6.6 seconds, which is a **700% speedup**. The total featurization time for the Tungsten example decreased from 15 minutes 20 seconds in #116 to just 3 minutes 37 seconds (with 16 cores on my server).

### CODE REVIEW

**Comment by sunghjung3** [comment]
**UPDATE**: I have figured out a very easy way to filter all-ghost triplets on an individual triplet level instead of checking the entirety of the neighbor list first, and this also cuts the unnecessary computations by a good chunk. Again, these changes do not change any of the resulting feature values.

I have moved the if-statement inside `generate_triplets()`, in which the 3-body neighbor mesh used to be generated like `j_arr, k_arr = np.meshgrid(i_group, i_group)`. With the newest changes, the meshes are generated by `j_arr, k_arr = np.meshgrid(i_group_filtered, i_group)`, where `i_group_filtered` only includes real atoms if `i_value` (the central atom) is a ghost atom. For illustration, if the `i_group` of a central ghost atom has no real atoms, then the mesh will return an empty array, as like before. But also now, if `i_group` has only 1 real atom and 25 ghost atoms, it now returns a mesh with 26 entries, whereas previously it would have returned a mesh of 26^2 == 676 entries.

This change cut down the 3-body force featurization time of the last structure in the Tungsten dataset to just 5.0 seconds, which is a **932%** speedup.

**Comment by sunghjung3** [comment]
I've also made the changes for 2-body force featurization, and it gives roughly a 4.4x speedup on the 2-body force featurization part but only a tiny change in the whole featurization speed because the 3-body force dominates the time.

The change was made in the `derivatives_by_interaction()` function, where the bottom `(N-n) x (N-n)` block of the supercell distance matrix is masked out, where `N` is the number of atoms in the supercell and `n` is the number of atoms in the unit cell.

With all these changes, the total time to featurize the Tungsten dataset is 3 minutes 25 seconds with 16 cores (but it must be noted that the parallelization is not ideal, since it batches over structures and not atoms; it takes about 90 seconds for the first 98.5% of the dataset).

I've verified that the features and the model for the Tungsten example are the same as before. Also, all the unit tests that test the feature values all pass. However, there are 2 unit tests in `test_distances.py` that fail: `TestUnary::test_distance_derivatives` and `TestBinary::test_distance_derivatives`. These unit tests count the number of distances returned from `derivatives_by_interaction()`, which is obviously going to be different because it filters out a lot of the unnecessary distances.

I will look over this further and make changes to the pytest after further discussion with other developers.

**Comment by monk-04** [comment]
I have checked the code for accuracy. It gives accurate features that numerically match the current version.

The code is also fast. On a 32 core job the current version needs about 1hr 20mins.
@sunghjung3 version needs about 7mins 22sec. Nice work @sunghjung3!!
 

I will give detailed comments on the code at a later time.

**Comment by sunghjung3** [comment]
Since the changes seem accurate, I have corrected the assertion values in the failing unit tests.

**Review by sxie22 — APPROVED** [review]

**Comment by sunghjung3** [comment]
I have not changed any code since @sxie22 's approval of this PR, but all the sudden the pull requests are failing. Here is the error message from the tests:

> A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
>
>If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

These seem to be triggered by `import tables` and `import ndsplines` and its incompatibility with Numpy 2.x.x, which was released just 5 days ago on June 16th, 2024. On my local computer, which uses Numpy 1.26.4, all the tests still pass.

If we are ok with pinning down the Numpy version to the latest 1.x.x, I think the change we need to make is add this line in the file `.github/workflows/tests.yml`:

    pip install numpy==1.26.4

**Comment by monk-04** [comment]
@sunghjung3 What we can do is hard code the numpy version to the most latest version which works.
After couple of months we will change the hard coded version. What do you say?

**Comment by sunghjung3** [comment]
@monk-04 I've pinned the Numpy version to 1.26.4 (the latest version 1) other than for Python 3.8, which doesn't support Numpy versions newer than 1.24.4.

**Review by monk-04 — APPROVED** [review]

**Pull request merged**
