### PR TITLE
generate_triplets bug fix

### PR DESCRIPTION
**Pull request by sunghjung3**
The main fix is in `uf3.representation.angles.py: generate_triplets()`. All other changes are just to accommodate for the change in the arguments of `generate_triplets()`.

The fix starts in line 437 of `angles.py`, where the distance triplets in the `ituples` is ordered by the corresponding element order given by `interaction_tuple`.

I tried to change things as little as possible, but this fact made it hard to find a minimal change:

- the interaction tuples are written in terms of **atomic symbols** and ordered by **electronegativity** (given in `uf3.data.composition.py`)
- the hashing must be done with **atomic numbers** ordered by **atomic number**

If the core developers are open to big changes that restructure how the interaction tuples are made and whether hashes should be/not be used, I am also open to the change.

### CODE REVIEW

**Comment by monk-04** [comment]
This is a critical bug. The core of the bug arises from the fact that, as pointed out by @sunghjung3, two different sorting methods are used-

1. For generating interaction tuple (and the bspline basis set) eg C-Pt-C, Pauling electro-negativity is used to sort elements at 1 and 2.
2. For generating interaction hashes the elements at 1 and 2 position (Pt and C in the above example) are sorted by atomic 

This bug produces different representation for symmetrically identical structures

Let's say I have two structures in POSCAR format-
Structure1
```
C0 Pt1 C2
1.0
30 0 0
0 30 0
0 0 30
C Pt C
1 1 1
Cart
0 0 0
0 3 0
0 0 4
```
Structure2
```
C1 C2 Pt3
1.0
30 0 0
0 30 0
0 0 30
C C Pt
1 1 1
Cart
0 0 0
0 0 4
0 3 0
```

Because of this bug the representation produced for these two structures will be different, even though they are the same structure (just the ordering of atoms is different).

This bug originates when inconsistency is introduced by sorting the `comp_tuple` by atomic number for generating the hashes ([in this line](https://github.com/uf3/uf3/blob/0fd1f3e74e329edb8fa67e0e425a21afc1dce40f/uf3/representation/angles.py#L423)), but the `tuples` that contains the atom order read from the POSCAR file is not sorted. Moreover it is further compounded by sorting the interactions by electronegativity.


@sunghjung3 What do you think of the following solution (look for the `Proposed changes` keyword)? Though it is not an elegant solution but it only makes local changes. We are open to big changes (for example sorting only by atomic number for everything) but we will need to discuss them with the entire team.

```
def generate_triplets(i_where,
                      j_where,
                      sup_composition,hashes,distance_matrix,knot_sets):
    """
    Identify unique "i-j-j'" tuples by combining provided i-j pairs, then
    compute i-j, i-k, and j-k pair distances from i-j-k tuples,
        distance matrix, and knot sequence for cutoffs.

    TODO: refactor to break up into smaller, reusable functions

    Args:
        i_where (np.ndarray): sorted "i" indices
        j_where (np.ndarray): sorted "j" indices
        sup_composition (np.ndarray): composition given by atomic numbers.
        hashes (np.ndarray): array of unique integer hashes for interactions.
        distance_matrix (np.ndarray): pair distance matrix.
        knot_sets (np.ndarray): list of lists of knot sequences per interaction

    Returns:
        tuples_idx (np.ndarray): array of shape (n_triangles, 3)
    """
    n_hashes = len(hashes)
    # find unique values of i (sorted such that i < j)
    i_values, group_sizes = np.unique(i_where, return_counts=True)
    # group j by values of i
    i_groups = np.array_split(j_where, np.cumsum(group_sizes)[:-1])
    # generate j-k combinations
    for i in range(len(i_groups)):
        tuples = np.array(np.meshgrid(i_groups[i],
                                      i_groups[i])).T.reshape(-1, 2)
        tuples = np.insert(tuples, 0, i_values[i], axis=1)
        comp_tuples = sup_composition[tuples]
        #comp_tuples[:, 1:] = np.sort(comp_tuples[:, 1:], axis=1)
        
        #Proposed changes
        sort_indices = np.argsort(comp_tuples[:, 1:],axis=1)
        comp_tuples_slice = np.take_along_axis(comp_tuples[:, 1:],sort_indices,axis=1)
        tuples_slice = np.take_along_axis(tuples[:, 1:],sort_indices,axis=1)
        
        comp_tuples = np.hstack((comp_tuples[:, [0]], comp_tuples_slice))
        tuples = np.hstack((tuples[:, [0]], tuples_slice))
        
        ijk_hash = composition.get_szudzik_hash(comp_tuples)

        grouped_triplets = [None] * n_hashes
        for j, hash_ in enumerate(hashes):
            ituples = tuples[ijk_hash == hash_]
            icomp_tuples = comp_tuples[ijk_hash == hash_]
            if len(ituples) == 0:
                grouped_triplets[j] = None
                continue
            # atoms j and k are interchangable; filter
            comparison_mask = (ituples[:, 1] != ituples[:, 2])
            ituples = ituples[comparison_mask]
            icomp_tuples = icomp_tuples[comparison_mask]
            #Proposed changes
            if len(ituples) > 1:
                ituples = np.array([ituples[0]])
                icomp_tuples = np.array([icomp_tuples[0]])
                #sort by electro-negativity as the interaction tuple is always
                #sorted by electro-negativity
                en_j = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][1]]]
                en_k = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][2]]]
                if  en_k < en_j:
                    ituples = np.array([[ituples[0][0],ituples[0][2],ituples[0][1]]])
                    
            # extract distance tuples
            r_l = distance_matrix[ituples[:, 0], ituples[:, 1]]
            r_m = distance_matrix[ituples[:, 0], ituples[:, 2]]
            r_n = distance_matrix[ituples[:, 1], ituples[:, 2]]
            # mask by longest distance
            l_mask = ((r_l >= knot_sets[j][0][0])
                      & (r_l <= knot_sets[j][0][-1]))
            m_mask = ((r_m >= knot_sets[j][1][0])
                      & (r_m <= knot_sets[j][1][-1]))
            n_mask = ((r_n >= knot_sets[j][2][0])
                      & (r_n <= knot_sets[j][2][-1]))
            dist_mask = np.logical_and.reduce([l_mask, m_mask, n_mask])
            r_l = r_l[dist_mask]
            r_m = r_m[dist_mask]
            r_n = r_n[dist_mask]
            ituples = ituples[dist_mask]
            
            if len(ituples) ==0:
                grouped_triplets[j] = None
            else:
                grouped_triplets[j] = i, r_l, r_m, r_n, ituples
            #grouped_triplets[j] = i, r_l, r_m, r_n, ituples
        yield grouped_triplets
```

**Comment by monk-04** [comment]
@JasonGibsonUfl just pushed a unit-test that tests for the above bug. The solution that I proposed passes the test.

**Comment by sunghjung3** [comment]
I have a comment about the following part:

            #Proposed changes
            if len(ituples) > 1:
                ituples = np.array([ituples[0]])
                icomp_tuples = np.array([icomp_tuples[0]])
                #sort by electro-negativity as the interaction tuple is always
                #sorted by electro-negativity
                en_j = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][1]]]
                en_k = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][2]]]
                if  en_k < en_j:
                    ituples = np.array([[ituples[0][0],ituples[0][2],ituples[0][1]]])

Most often, `ituples` has multiple rows. Same for `icomp_tuples`. Shouldn't we have a loop or something similar where we do this `en_k < en_j` comparison for each and every row?

**Comment by monk-04** [comment]
Nice catch @sunghjung3!

Here's the relevant part of the updated code that will solve the issue-
```

        for j, hash_ in enumerate(hashes):
            ituples = tuples[ijk_hash == hash_]
            icomp_tuples = comp_tuples[ijk_hash == hash_]
            if len(ituples) == 0:
                grouped_triplets[j] = None
                continue
            
            #Check if same neighbouring elements
            if icomp_tuples[0][1] == icomp_tuples[0][2]:
                # element at j and k are same;
                #remove redundant interactions
                comparison_mask = (ituples[:, 1] < ituples[:, 2])
                ituples = ituples[comparison_mask]
                icomp_tuples = icomp_tuples[comparison_mask]

            else:
                #Elements at j and k not same
                #cordinates of j and k are same; filter eg 011, 022, 033
                #this comparison mask is redundant
                comparison_mask = (ituples[:, 1] != ituples[:, 2])

                ituples = ituples[comparison_mask]
                icomp_tuples = icomp_tuples[comparison_mask]
                
                if len(ituples)>0:
                    #Remove repetitive interactions
                    ituples = np.unique(ituples,axis=0)
                    icomp_tuples = np.unique(icomp_tuples,axis=0)
                    
                    #sort by electro-negativity as the interaction tuple is always
                    #sorted by electro-negativity
                    en_j = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][1]]]
                    en_k = composition.reference_X[ase_symbols.chemical_symbols[icomp_tuples[0][2]]]
                    if  en_k < en_j:
                        # Interchange columns 1 and 2
                        ituples[:, [1, 2]] = ituples[:, [2, 1]]

            # extract distance tuples
            r_l = distance_matrix[ituples[:, 0], ituples[:, 1]]
            r_m = distance_matrix[ituples[:, 0], ituples[:, 2]]
            r_n = distance_matrix[ituples[:, 1], ituples[:, 2]]
```

**Comment by sunghjung3** [comment]
After a rough reading of the code, it looks alright. Please double-check if my interpretation is correct.

In this section:

            #Check if same neighbouring elements
            if icomp_tuples[0][1] == icomp_tuples[0][2]:
                # element at j and k are same;
                #remove redundant interactions
                comparison_mask = (ituples[:, 1] < ituples[:, 2])
                ituples = ituples[comparison_mask]
                icomp_tuples = icomp_tuples[comparison_mask]

We are relying on the fact that if the 2 neighbor elements are the same, the `tuples = np.hstack((tuples[:, [0]], tuples_slice))` line will not change the order of `tuples`, so it is still guaranteed (from the line involving `np.meshgrid`) that there will be one row with atom numbers `[a, b, c]` and another row with atom numbers [`a, c, b`].

And in the following line for the case of differing neighbor elements:

    icomp_tuples = np.unique(icomp_tuples,axis=0)

This `icomp_tuples` will always have shape `(1, 3)`.

**Comment by sunghjung3** [comment]
Also, can you clarify what `ase_symbols` is? I assumed that the correct import was `from ase.data import chemical_symbols as ase_symbols`, but now I see that it is used as `ase_symbols.chemical_symbols`. This is why the tests failed above.

Should it just be `import ase.data as ase_symbols`? If so, what not call it `ase_data` instead?

**Comment by sunghjung3** [comment]
Never mind. Fixed.

**Comment by monk-04** [comment]
@sunghjung3 Your interpretation is correct.

Waiting @JasonGibsonUfl  to take a look at the code. If everyone agrees we can merge and close this pull request.

**Comment by JasonGibsonUfl** [comment]
The solution seems reasonable. I am approving this pull request. However, the equal electronegativity unit test is still falling. The solution @sunghjung3 proposed of  "the hashing must be done with atomic numbers ordered by atomic number" seems like the most viable path forward.

**Comment by sunghjung3** [comment]
@monk-04 The force-push was because your proposed fix was so vastly different than my fix, so I had to re-checkout the latest master, write the newest fix in to `generate_triplets()`, and then cherry-pick all the additional commits that you and Jason made (I think all about unit tests)

**Pull request merged**
