### PR TITLE
Added uniform/non-unifrom feature to UF3 LAMMPS

### PR DESCRIPTION
**Pull request by monk-04**
For uniform knot spacing the evaluation of indices of knots that surround a given atom distance can be done by a simple code-

`3+(int)((r-knot_vect[0])/knot_spacing);`

Whereas for non-uniform knot spacing, we need to use a loop over all knots.

This pull request implements this feature.

There is a noticeable speed-up in LAMMPS simulation for uniform knots as compared to the previous version-
image

Plot made by @JasonGibsonUfl 

Changes, necessary for the above feature to work, were made to the UF3 LAMMPS POT files format and the file parser. Both the document describing the POT file format and the script to produce these files have been updated.

Also, the old format of specifying all the UF3 LAMMPS POT files in one line is now deprecated.

### CODE REVIEW

**Comment by matthias-rupp** [comment]
Dear @monk-04 

The merge request looks reasonable to me 👍 

The linear-search non-uniform knot location could maybe be improved by binary search (with branch-free terminal cases, similar to how efficient sorting is implemented). However, we should _not_ consider this now. When the codebase has stabilized more it could be worth revisiting.

Question: Some checks fail (3.8, 3.9, 3.10, 3.11). Is that due to a problem in the merged code or unrelated?

Kind regards,
Matthias

**Comment by monk-04** [comment]
Thank you for your comments Dr @matthias-rupp . 

One another improvement I have in mind for the non-uniform knot search is to start from the farthest knot and work backward.

The checks failed because of the following errors-

```
      ERROR: Ignored the following versions that require a different python version: 2.2.8 Requires-Python <4,>=3.9
      ERROR: Could not find a version that satisfies the requirement blosc2>=2.2.8 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.5.1, 0.5.2, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7)
      ERROR: No matching distribution found for blosc2>=2.2.8
```

It seems unrelated to the changes I made.

**Comment by monk-04** [comment]
@matthias-rupp I re-ran the tests, all of them are passing

**Review by sxie22 — APPROVED** [review]

**Review by matthias-rupp — APPROVED** [review]
Dear @monk-04 

Thanks, looks good to me now.

Kind regards,
Matthias

**Comment by monk-04** [comment]
Merging to develop.

**Pull request merged**
