### PR TITLE
fix loss function weights and regularizer bug (redo)

### PR DESCRIPTION
**Pull request by sunghjung3**
Properly merge #85 to develop branch

### CODE REVIEW

**Review by sxie22 — APPROVED** [review]
Here are my observations. If they are correct, we should incorporate similar notes into the changelog.

1) Files model_pair.json and model_uf23.json are deleted. They were in the previous format, with "compressed" vector coefficients rather than "uncompressed" arrays.
2) Fix in loss function means new values for lambda are changed by a power of 2 compared to previous values of lambda (e.g. 2 becomes 4, 0.5 becomes 0.25).
3) Fixes in the loss function means that the energy-force weight (kappa) has been changed by a data-specific factor involving the number of energy and force observations. This should be re-optimized, but 0.5 now (properly) corresponds to equal weighting of energy and forces.

**Comment by monk-04** [comment]
@sunghjung3 @sxie22 We are still using try and except in least_squares.py

**Review by JasonGibsonUfl — APPROVED** [review]
looks good

**Comment by sunghjung3** [comment]
@monk-04 I am planning to incorporate that in the next pull request. The thing is that the singlepoint_bug involves the same lines of code, so I need to either clump multiple issues all into a single pull request, or do them one by one

**Comment by monk-04** [comment]
@sunghjung3 Cool!

**Pull request merged**
