### PR TITLE
Merge Symmetry_updates to `develop`

### PR DESCRIPTION
**Pull request by sunghjung3**
Merge `Symmetry_updates` branch to `develop`.

### CODE REVIEW

**Review by sxie22 — APPROVED** [review]

**Comment by JasonGibsonUfl** [comment]
@sunghjung3 Can you elaborate on what effect this change will have?

**Comment by sunghjung3** [comment]
@JasonGibsonUfl This is a follow-up pull request from #77 . It is just a more concise implementation of `generate_triplets()`, which should not affect any results.

**Comment by sunghjung3** [comment]
When tested on the tungsten dataset, this version of `generate_triplets()` is 1.27 times faster than the current master's version (49m 37.7s vs 63m 4.4s).

And I verified that the 2 dataframes are identical, up to numerical precision (compared using `np.allclose(df_features_1, df_features_2, rtol=1e-5, atol=1e-8)`)

**Review by JasonGibsonUfl — APPROVED** [review]
looks good

**Pull request merged**
