### PR TITLE
Regulariztion bugfix

### PR DESCRIPTION
**Pull request by sunghjung3**
This pull request includes several bugfixes and enhancements related to 3-body regularization matrices.

-  3 commits on Oct 1, 2023 and commit `226d7e5` on Oct 22, 2023:
    - Fixed issue 3 in the attached docx file (issues 1 and 2 were fixed in #85 ).
- Commit `0b1e409` on Oct 2, 2023:
    - Fixed issue 4 and 5 in the attached docx file. Also illustrated in the attached pptx file.
- Commit `9857b3c` on Oct 2, 2023 and commit `a882598` on Oct 18, 2023:
    - 3-body regularization center value adjustment (see attached pptx file).
- First 5 commits on Oct 17, 2023:
    - Clean up and refactoring regularizer-related methods in `uf3/representation/bspline.py` and `uf3/regression/regularize.py`
- Last commit on Oct 17, 2023 and first commit on Oct 18, 2023:
    - Unit tests for regularization matrices (see attached pptx file)

After all the changes, I ran some hyperparameter optimizations on the tungsten dataset to find the optimal `kappa` and `lambda` values. While many different sets of `lambda` values seemed to give similar results, it strongly showed that `kappa=0.8` is the best value for balancing both energy and force errors. The Jupyter notebooks and `.json` files for the tungsten example have been updated with these new hyperparameter values.

---
Docx file:
[loss_function_weights_math.docx](https://github.com/uf3/uf3/files/13065436/loss_function_weights_math.docx)

Pptx file:
[regularization_3b.pptx](https://github.com/uf3/uf3/files/13065469/regularization_3b.pptx)

### CODE REVIEW

**Comment by sunghjung3** [comment]
When generating frozen indices (`uf3/representation/bspline.py BsplineBasis.generate_frozen_indices()`), there is an option to set the trimmed coefficients to a nonzero value (but the default is 0). However, the current implementation of `generate_frozen_indices()` only applies the value to 2-body but is not carried over to 3-body. In addition, nowhere in the entire UF3 code is this custom nonzero value passed in, so I am guessing that this feature is either deprecated or unimportant. Ideally, the effect of freezing a coefficient to a nonzero value should be reflected when freezing the regularize, but I will leave this part unchanged because this feature seems unimportant or deprecated.

If we eventually decide to fix the nonzero freezing feature (even for 3-body), then a partial change to freezing the regularize would be something like:

        #regularizer = freeze_regularizer(self.regularizer, self.mask)  # OLD
        regularizer, reg_y = freeze_columns(self.regularizer,
                                            np.zeros(len(self.regularizer)),
                                            self.mask,
                                            self.frozen_c,
                                            self.col_idx)  # if np.all(self.frozen_c == 0), then reg_y == 0

Depending on this eventual fix, the 3-body regularization matrix compression may need to take place in `uf3/representation/bspline.py BSplineBasis.get_regularization_matrix_3b()`.

**Review by JasonGibsonUfl — APPROVED** [review]
This looks great! I am approving this pull request.

**Comment by monk-04** [comment]
@sunghjung3 I don't understand your last comment. I am going to need some more time to go over it

**Comment by sunghjung3** [comment]
@monk-04 Sure. Take your time.

To provide more context, it is just because of a minor detail that arises from the feature to freeze some 2-body coefficients to a user-provided nonzero value. For instance, if we have a curvature regularization `c_1 - 2*c_2 + c_3 == 0` and the user wants to freeze `c_3` to `1.0`, then I believe the curvature regularization should be updated accordingly when `c_3` is frozen, like `c_1 - 2*c_2 == -1`.

Currently, this regularization update for nonzero frozen coefficients is not implemented in UF3. I was going to implement it, but this required some semi-significant changes. And I wasn't sure if this feature was deprecated or not, so I left it unchanged.

**Pull request merged**
