### PR TITLE
Revert "fix loss function weights and regularizer bug"

### PR DESCRIPTION
**Pull request by sxie22**
Branch protection was not properly implemented for the dev branch so #85 was prematurely merged. This pull request will be closed if reviewers are satisfied with #85.

### CODE REVIEW

**Comment by monk-04** [comment]
The tungsten model .json files are being changed in this pull request. Are we sure that none of those models are used in the paper? @sxie22

**Comment by JasonGibsonUfl** [comment]
I approve

**Comment by monk-04** [comment]
I approve the reversion

**Comment by sunghjung3** [comment]
@monk-04 I reran the Tungsten example with the new changes. I thought I was told by someone to rerun the examples with the new changes.

**Comment by sxie22** [comment]
@monk-04 No worries, the models used for the paper are in uf3/supplement/potentials.

The changes in this pull request alter the energy/force weight balance, so the potentials will be different. On the other hand, it should be possible to select a value for the weight that recovers the previous models.

**Pull request merged**
